- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy NGINX config template
  template:
    src: webapp.conf.j2
    dest: /etc/nginx/sites-available/webapp.conf
  notify: Reload NGINX

- name: Enable NGINX site config
  file:
    src: /etc/nginx/sites-available/webapp.conf
    dest: /etc/nginx/sites-enabled/webapp.conf
    state: link
    force: yes

- name: Remove default site config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart NGINX
  service:
    name: nginx
    state: restarted
