- name: Add Docker GPG key and repo
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  args:
    warn: false

- name: Install Docker CE
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present

- name: Install Docker SDK for Python
  pip:
    name: docker

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Docker login
  docker_login:
    registry_url: "{{ registry_url }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"

- name: Run containers
  docker_container:
    name: "webapp_{{ item }}"
    image: "{{ docker_image }}"
    restart_policy: always
    published_ports:
      - "800{{ item }}:{{ app_port }}"
    state: started
  loop: "{{ range(1, container_count + 1) | list }}"
