- name: Docker GPG 
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
  
- name: Ensure docker is running
  service: 
    name: docker
    state: started
    enabled: true

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present

- name: Docker login
  docker_login:
    registry_url: "{{ registry_url }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"

- name: Run containers
  docker_container:
    name: "webapp_{{ item }}"
    image: "{{ docker_image }}"
    restart_policy: always
    published_ports:
      - "800{{ item }}:{{ app_port }}"
    state: started
  loop: "{{ range(1, container_count + 1) | list }}"
