apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: cloude_app
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "mclov",
          "password": ""
        }
      }
    }